version: "3.8"

services:
  db:
    image: postgres:16  # Updated from postgres:14
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: web_container
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=development
      - PORT=${PORT}
      - ML_SERVICE_URL=http://ml_service:5000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    networks:
      - app-network

  ml_service:
    build:
      context: ./ml_trainer
      dockerfile: Dockerfile
    container_name: ml_service_container
    restart: unless-stopped
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
    volumes:
      - ./ml_trainer:/app
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
